app_name: Test Model
metrics_port: 0
enable_kafka: true

model_conf:
  name: dummy_v1
  type: DummyModel
  artefacts:
    model: bert.pt
  hparams:
    size: 128
    mode: base

kafka_conf:
  consume_topic: test-topic
  produce_topic: test-topic-out

  consumer_conf:
    bootstrap_servers: localhost:9092
    group_id: sameli
    auto_offset_reset: latest
  producer_conf:
    bootstrap_servers: localhost:9092

http_conf:
  host: 127.0.0.1
  port: 8000
  loop: uvloop